"""
app/utils/storage.py — one storage interface for branding-workspace
media (logo source, exported post PNG, rendered story video/GIF), two
backends: local filesystem for development, Cloudflare R2 for
production, switched by the STORAGE_BACKEND env var ("local" | "r2") —
never by which code path a caller takes. Callers only ever talk to
get_storage()'s return value.

The database (models.BrandAsset.storage_key) stores the KEY this
returns, never the bytes — deliberately NOT the Media/ArtisanPhoto
LargeBinary-column pattern used for resumes/avatar photos. That pattern
is fine for a few KB of resume text or a small avatar; it doesn't scale
to a rendered story video, and it means every read of a media file is a
database round-trip instead of a CDN-cacheable object fetch.
"""
import os
import uuid

R2_ACCOUNT_ID_ENV = "R2_ACCOUNT_ID"
R2_ACCESS_KEY_ENV = "R2_ACCESS_KEY_ID"
R2_SECRET_KEY_ENV = "R2_SECRET_ACCESS_KEY"
R2_BUCKET_ENV = "R2_BUCKET"
R2_PUBLIC_BASE_ENV = "R2_PUBLIC_URL_BASE"


class StorageBackend:
    def put(self, key, data, content_type=None):
        """Stores bytes under key. Returns the key (callers already have
        it; returning it back keeps put()'s call sites symmetrical with
        get()/url()/delete(), which all take a key as their one arg)."""
        raise NotImplementedError

    def get(self, key):
        raise NotImplementedError

    def url(self, key):
        """A URL a browser can fetch directly."""
        raise NotImplementedError

    def delete(self, key):
        raise NotImplementedError


class LocalStorage(StorageBackend):
    """Dev-only. Writes under backend/instance/brand_storage/<key> — Flask's
    own conventional per-instance data directory, already gitignored the
    same way instance/resume.db (the SQLite dev fallback) is. Served back
    via a plain GET route (api/brand_workspace.py's /assets/<path:key>)
    since there's no public bucket URL to hand out locally the way R2
    has one."""

    def __init__(self, root=None):
        self.root = root or os.path.join(
            os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
            "instance", "brand_storage",
        )
        os.makedirs(self.root, exist_ok=True)

    def _path(self, key):
        # key is always generated by make_key() below (workspace_id/kind/
        # uuid.ext) — never taken verbatim from a request — so there's no
        # path-traversal surface despite the plain os.path.join.
        return os.path.join(self.root, key)

    def put(self, key, data, content_type=None):
        path = self._path(key)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as f:
            f.write(data)
        return key

    def get(self, key):
        with open(self._path(key), "rb") as f:
            return f.read()

    def url(self, key):
        return f"/api/v1/workspace/assets/{key}"

    def delete(self, key):
        try:
            os.remove(self._path(key))
        except FileNotFoundError:
            pass


class R2Storage(StorageBackend):
    """Cloudflare R2 — S3-compatible, so this is boto3's S3 client
    pointed at R2's own endpoint, nothing R2-specific in the client
    itself. Raises clearly at CONSTRUCTION if any required env var is
    missing, rather than failing opaquely on the first real upload —
    same "fail fast with a fixable message" shape GROQ_API_KEY/
    MAIL_USERNAME checks already use elsewhere in this app."""

    def __init__(self):
        import boto3

        account_id = os.environ.get(R2_ACCOUNT_ID_ENV)
        access_key = os.environ.get(R2_ACCESS_KEY_ENV)
        secret_key = os.environ.get(R2_SECRET_KEY_ENV)
        self.bucket = os.environ.get(R2_BUCKET_ENV)
        self.public_base = (os.environ.get(R2_PUBLIC_BASE_ENV) or "").rstrip("/")
        missing = [
            name for name, val in [
                (R2_ACCOUNT_ID_ENV, account_id), (R2_ACCESS_KEY_ENV, access_key),
                (R2_SECRET_KEY_ENV, secret_key), (R2_BUCKET_ENV, self.bucket),
            ] if not val
        ]
        if missing:
            raise RuntimeError(f"STORAGE_BACKEND=r2 but not configured: missing {', '.join(missing)}")

        self.client = boto3.client(
            "s3", endpoint_url=f"https://{account_id}.r2.cloudflarestorage.com",
            aws_access_key_id=access_key, aws_secret_access_key=secret_key,
            region_name="auto",
        )

    def put(self, key, data, content_type=None):
        self.client.put_object(Bucket=self.bucket, Key=key, Body=data, ContentType=content_type or "application/octet-stream")
        return key

    def get(self, key):
        return self.client.get_object(Bucket=self.bucket, Key=key)["Body"].read()

    def url(self, key):
        if self.public_base:
            return f"{self.public_base}/{key}"
        # No public bucket domain configured — a time-limited signed GET
        # instead of a permanent link, so this backend still WORKS
        # (rather than raising) with just the four required env vars set.
        return self.client.generate_presigned_url("get_object", Params={"Bucket": self.bucket, "Key": key}, ExpiresIn=3600)

    def delete(self, key):
        self.client.delete_object(Bucket=self.bucket, Key=key)


_backend = None


def get_storage():
    """Constructed once, cached — R2Storage's constructor does real
    env-var validation and builds a boto3 client, not free work to repeat
    per-request. Swapping STORAGE_BACKEND requires a process restart to
    take effect, same as every other env-var-driven config in this app."""
    global _backend
    if _backend is None:
        which = (os.environ.get("STORAGE_BACKEND") or "local").strip().lower()
        _backend = R2Storage() if which == "r2" else LocalStorage()
    return _backend


def make_key(workspace_id, kind, ext):
    """workspace_id/kind/<uuid>.ext — the workspace_id PREFIX is what
    makes a directory listing (or an R2 bucket browse) already sorted by
    workspace with no separate index needed; the uuid segment is what
    makes the key itself unguessable, same reasoning as every token in
    this feature."""
    return f"{workspace_id}/{kind}/{uuid.uuid4().hex}.{ext.lstrip('.')}"
